"use client";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  UserButton,
} from "@clerk/nextjs/app-beta";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedIn>
            {children}
            <UserButton />
          </SignedIn>
          <SignedOut>
            <SignIn redirectUrl={"/"} />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
