import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
} from "@clerk/nextjs/app-beta/";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedIn>{children}</SignedIn>
          <SignedOut>
            <div
              style={{
                display: "flex",
                width: "100vw",
                height: "100vh",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <SignIn
                appearance={{
                  elements: {
                    card: {
                      // width: window?.innerWidth <= 1000 ? "90vw" : "auto",
                      // height: window?.innerWidth <= 1000 ? "70vh" : "auto",
                      // width: "90vw",
                      // height: "70vh",
                    },
                  },
                }}
              />
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
